version: '2'
services:
  web:
    container_name: odoo_12
    image: odoo:12
    depends_on:
      - db
    ports:
      - "$port:8069"
      - "$chat_port:8072"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo/
      - ./addons:/mnt/extra-addons
  db:
    container_name: db_12
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
